default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: my_andromeda_app_development

production:
  <<: *default
  database: my_andromeda_app_production

cable:
  <<: *default
  database: my_andromeda_app_cache

queue:
  <<: *default
  database: my_andromeda_app_queue

cache:
  <<: *default
  database: my_andromeda_app_cache
